### ISSUE TITLE
Typo in function name

### ISSUE THREAD

**Issue by VivekThazhathattil** [nathanrooy/simulated-annealing#3]
https://github.com/nathanrooy/simulated-annealing/blob/42eb34e761b76692882a3905ec2be48e19e8133e/simulated_annealing/sa.py#L77

This should be ` self.update_t = self.cooling_exponential_m`

**Comment by nathanrooy** [comment]
Thanks @VivekThazhathattil!

**Comment by nathanrooy** [comment]
Thanks @VivekThazhathattil!
